title: UIT-INF-2203
description: The course provides a thorough introduction to operating system.
  Topics include threads and processes, process coordination and synchronization, physical and virtual storage organization, interrupt handling, peripheral devices and file systems.
  The exercises include both analysis of abstractions, and their design and implementation.
  During the course each student will develop a running operating system kernel for an Intel x86 based computer.
theme: just-the-docs
baseurl: ""
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


# Site settings
logo: /public/uit-top.png
image: /public/uit-logo.png

# Contact information (person)
contact:
  email: john.markus.bjorndalen@uit.no
  name: John Markus Bj√∏rndalen

# Makes navigation links open in a new tab
nav_external_links_new_tab: true

# Aux links for the upper right navigation
aux_links:
  "2201 on GitHub":
    - "https://github.com/uit-inf-2201"

  "2201 on Canvas":
    - "https://uit.instructure.com/"

nav_external_links:
  - title: Lectures on Canvas
    url: https://uit.instructure.com/courses/36446/files/folder/Lectures


# Document collections
collections:
  lectures:
    output: true

just_the_docs:
  collections:
    lectures:
      name: Lectures
